### ISSUE TITLE
'Create & Upload' Function not able to encode character

### ISSUE THREAD

**Issue by tumms** [mfuentesg/SyncSettings#172] opened 2020-06-29 19:46 UTC
Error Message:
"'latin-1' codec can't encode character '\u052c' in position 124995: ordinal not in range(256)"

[sync.log](https://github.com/mfuentesg/SyncSettings/files/4847697/sync.log)

**Comment by tumms** [comment] 2020-06-29 19:47
ERROR:Sync Settings.sync_settings.libs.logger:'latin-1' codec can't encode character '\u052c' in position 124959: ordinal not in range(256)
Traceback (most recent call last):
  File "C:\Users\tylerS\AppData\Roaming\Sublime Text 3\Installed Packages\Sync Settings.sublime-package\sync_settings/commands/upload.py", line 28, in upload
    data={'files': files}
  File "C:\Users\tylerS\AppData\Roaming\Sublime Text 3\Installed Packages\Sync Settings.sublime-package\sync_settings/libs/gist.py", line 36, in auth_wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\tylerS\AppData\Roaming\Sublime Text 3\Installed Packages\Sync Settings.sublime-package\sync_settings/libs/gist.py", line 46, in with_gid_wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\tylerS\AppData\Roaming\Sublime Text 3\Installed Packages\Sync Settings.sublime-package\sync_settings/libs/gist.py", line 73, in update
    return self.__do_request('patch', self.make_uri(gid), data=sublime.encode_value(data, True)).json()
  File "C:\Users\tylerS\AppData\Roaming\Sublime Text 3\Installed Packages\Sync Settings.sublime-package\sync_settings/libs/gist.py", line 92, in __do_request
    response = getattr(requests, verb)(url, headers=self.headers, proxies=self.proxies, **kwargs)
  File "C:\Users\tylerS\AppData\Roaming\SUBLIM~1\Packages\requests\all\requests\api.py", line 140, in patch
    return request('patch', url,  data=data, **kwargs)
  File "C:\Users\tylerS\AppData\Roaming\SUBLIM~1\Packages\requests\all\requests\api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\tylerS\AppData\Roaming\SUBLIM~1\Packages\requests\all\requests\sessions.py", line 522, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\tylerS\AppData\Roaming\SUBLIM~1\Packages\requests\all\requests\sessions.py", line 642, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\tylerS\AppData\Roaming\SUBLIM~1\Packages\requests\all\requests\adapters.py", line 439, in send
    timeout=timeout
  File "C:\Users\tylerS\AppData\Roaming\SUBLIM~1\Packages\requests\all\requests\packages\urllib3\connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "C:\Users\tylerS\AppData\Roaming\SUBLIM~1\Packages\requests\all\requests\packages\urllib3\connectionpool.py", line 356, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "./python3.3/http/client.py", line 1065, in request
  File "./python3.3/http/client.py", line 1102, in _send_request
UnicodeEncodeError: 'latin-1' codec can't encode character '\u052c' in position 124959: ordinal not in range(256)
ERROR:Sync Settings.sync_settings.libs.logger:'latin-1' codec can't encode character '\u052c' in position 124995: ordinal not in range(256)
Traceback (most recent call last):
  File "C:\Users\tylerS\AppData\Roaming\Sublime Text 3\Installed Packages\Sync Settings.sublime-package\sync_settings/commands/create_and_upload.py", line 45, in create
    ).create(data)
  File "C:\Users\tylerS\AppData\Roaming\Sublime Text 3\Installed Packages\Sync Settings.sublime-package\sync_settings/libs/gist.py", line 36, in auth_wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\tylerS\AppData\Roaming\Sublime Text 3\Installed Packages\Sync Settings.sublime-package\sync_settings/libs/gist.py", line 66, in create
    return self.__do_request('post', self.make_uri(), data=sublime.encode_value(data, True)).json()
  File "C:\Users\tylerS\AppData\Roaming\Sublime Text 3\Installed Packages\Sync Settings.sublime-package\sync_settings/libs/gist.py", line 92, in __do_request
    response = getattr(requests, verb)(url, headers=self.headers, proxies=self.proxies, **kwargs)
  File "C:\Users\tylerS\AppData\Roaming\SUBLIM~1\Packages\requests\all\requests\api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "C:\Users\tylerS\AppData\Roaming\SUBLIM~1\Packages\requests\all\requests\api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\tylerS\AppData\Roaming\SUBLIM~1\Packages\requests\all\requests\sessions.py", line 522, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\tylerS\AppData\Roaming\SUBLIM~1\Packages\requests\all\requests\sessions.py", line 642, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\tylerS\AppData\Roaming\SUBLIM~1\Packages\requests\all\requests\adapters.py", line 439, in send
    timeout=timeout
  File "C:\Users\tylerS\AppData\Roaming\SUBLIM~1\Packages\requests\all\requests\packages\urllib3\connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "C:\Users\tylerS\AppData\Roaming\SUBLIM~1\Packages\requests\all\requests\packages\urllib3\connectionpool.py", line 356, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "./python3.3/http/client.py", line 1065, in request
  File "./python3.3/http/client.py", line 1102, in _send_request
UnicodeEncodeError: 'latin-1' codec can't encode character '\u052c' in position 124995: ordinal not in range(256)
ERROR:Sync Settings.sync_settings.libs.logger:'latin-1' codec can't encode character '\u052c' in position 124959: ordinal not in range(256)
Traceback (most recent call last):
  File "C:\Users\tylerS\AppData\Roaming\Sublime Text 3\Installed Packages\Sync Settings.sublime-package\sync_settings/commands/upload.py", line 28, in upload
    data={'files': files}
  File "C:\Users\tylerS\AppData\Roaming\Sublime Text 3\Installed Packages\Sync Settings.sublime-package\sync_settings/libs/gist.py", line 36, in auth_wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\tylerS\AppData\Roaming\Sublime Text 3\Installed Packages\Sync Settings.sublime-package\sync_settings/libs/gist.py", line 46, in with_gid_wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\tylerS\AppData\Roaming\Sublime Text 3\Installed Packages\Sync Settings.sublime-package\sync_settings/libs/gist.py", line 73, in update
    return self.__do_request('patch', self.make_uri(gid), data=sublime.encode_value(data, True)).json()
  File "C:\Users\tylerS\AppData\Roaming\Sublime Text 3\Installed Packages\Sync Settings.sublime-package\sync_settings/libs/gist.py", line 92, in __do_request
    response = getattr(requests, verb)(url, headers=self.headers, proxies=self.proxies, **kwargs)
  File "C:\Users\tylerS\AppData\Roaming\SUBLIM~1\Packages\requests\all\requests\api.py", line 140, in patch
    return request('patch', url,  data=data, **kwargs)
  File "C:\Users\tylerS\AppData\Roaming\SUBLIM~1\Packages\requests\all\requests\api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\tylerS\AppData\Roaming\SUBLIM~1\Packages\requests\all\requests\sessions.py", line 522, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\tylerS\AppData\Roaming\SUBLIM~1\Packages\requests\all\requests\sessions.py", line 642, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\tylerS\AppData\Roaming\SUBLIM~1\Packages\requests\all\requests\adapters.py", line 439, in send
    timeout=timeout
  File "C:\Users\tylerS\AppData\Roaming\SUBLIM~1\Packages\requests\all\requests\packages\urllib3\connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "C:\Users\tylerS\AppData\Roaming\SUBLIM~1\Packages\requests\all\requests\packages\urllib3\connectionpool.py", line 356, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "./python3.3/http/client.py", line 1065, in request
  File "./python3.3/http/client.py", line 1102, in _send_request
UnicodeEncodeError: 'latin-1' codec can't encode character '\u052c' in position 124959: ordinal not in range(256)
WARNING:Sync Settings.sync_settings.libs.logger:{'message': 'Not Found', 'documentation_url': 'https://developer.github.com/v3/gists/#get-a-single-gist'}
ERROR:Sync Settings.sync_settings.libs.logger:The requested gist do not exists, or the token has not enough permissions
Traceback (most recent call last):
  File "C:\Users\tylerS\AppData\Roaming\Sublime Text 3\Installed Packages\Sync Settings.sublime-package\sync_settings/commands/download.py", line 45, in download
    ).get(settings.get('gist_id'))
  File "C:\Users\tylerS\AppData\Roaming\Sublime Text 3\Installed Packages\Sync Settings.sublime-package\sync_settings/libs/gist.py", line 46, in with_gid_wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\tylerS\AppData\Roaming\Sublime Text 3\Installed Packages\Sync Settings.sublime-package\sync_settings/libs/gist.py", line 83, in get
    return self.__do_request('get', self.make_uri(gid)).json()
  File "C:\Users\tylerS\AppData\Roaming\Sublime Text 3\Installed Packages\Sync Settings.sublime-package\sync_settings/libs/gist.py", line 98, in __do_request
    raise NotFoundError('The requested gist do not exists, or the token has not enough permissions')
Sync Settings.sync_settings.libs.gist.NotFoundError: The requested gist do not exists, or the token has not enough permissions
ERROR:Sync Settings.sync_settings.libs.logger:'latin-1' codec can't encode character '\u052c' in position 124995: ordinal not in range(256)
Traceback (most recent call last):
  File "C:\Users\tylerS\AppData\Roaming\Sublime Text 3\Installed Packages\Sync Settings.sublime-package\sync_settings/commands/create_and_upload.py", line 45, in create
    ).create(data)
  File "C:\Users\tylerS\AppData\Roaming\Sublime Text 3\Installed Packages\Sync Settings.sublime-package\sync_settings/libs/gist.py", line 36, in auth_wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\tylerS\AppData\Roaming\Sublime Text 3\Installed Packages\Sync Settings.sublime-package\sync_settings/libs/gist.py", line 66, in create
    return self.__do_request('post', self.make_uri(), data=sublime.encode_value(data, True)).json()
  File "C:\Users\tylerS\AppData\Roaming\Sublime Text 3\Installed Packages\Sync Settings.sublime-package\sync_settings/libs/gist.py", line 92, in __do_request
    response = getattr(requests, verb)(url, headers=self.headers, proxies=self.proxies, **kwargs)
  File "C:\Users\tylerS\AppData\Roaming\SUBLIM~1\Packages\requests\all\requests\api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "C:\Users\tylerS\AppData\Roaming\SUBLIM~1\Packages\requests\all\requests\api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\tylerS\AppData\Roaming\SUBLIM~1\Packages\requests\all\requests\sessions.py", line 522, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\tylerS\AppData\Roaming\SUBLIM~1\Packages\requests\all\requests\sessions.py", line 642, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\tylerS\AppData\Roaming\SUBLIM~1\Packages\requests\all\requests\adapters.py", line 439, in send
    timeout=timeout
  File "C:\Users\tylerS\AppData\Roaming\SUBLIM~1\Packages\requests\all\requests\packages\urllib3\connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "C:\Users\tylerS\AppData\Roaming\SUBLIM~1\Packages\requests\all\requests\packages\urllib3\connectionpool.py", line 356, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "./python3.3/http/client.py", line 1065, in request
  File "./python3.3/http/client.py", line 1102, in _send_request
UnicodeEncodeError: 'latin-1' codec can't encode character '\u052c' in position 124995: ordinal not in range(256)
ERROR:Sync Settings.sync_settings.libs.logger:'latin-1' codec can't encode character '\u052c' in position 124995: ordinal not in range(256)
Traceback (most recent call last):
  File "C:\Users\tylerS\AppData\Roaming\Sublime Text 3\Installed Packages\Sync Settings.sublime-package\sync_settings/commands/create_and_upload.py", line 45, in create
    ).create(data)
  File "C:\Users\tylerS\AppData\Roaming\Sublime Text 3\Installed Packages\Sync Settings.sublime-package\sync_settings/libs/gist.py", line 36, in auth_wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\tylerS\AppData\Roaming\Sublime Text 3\Installed Packages\Sync Settings.sublime-package\sync_settings/libs/gist.py", line 66, in create
    return self.__do_request('post', self.make_uri(), data=sublime.encode_value(data, True)).json()
  File "C:\Users\tylerS\AppData\Roaming\Sublime Text 3\Installed Packages\Sync Settings.sublime-package\sync_settings/libs/gist.py", line 92, in __do_request
    response = getattr(requests, verb)(url, headers=self.headers, proxies=self.proxies, **kwargs)
  File "C:\Users\tylerS\AppData\Roaming\SUBLIM~1\Packages\requests\all\requests\api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "C:\Users\tylerS\AppData\Roaming\SUBLIM~1\Packages\requests\all\requests\api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\tylerS\AppData\Roaming\SUBLIM~1\Packages\requests\all\requests\sessions.py", line 522, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\tylerS\AppData\Roaming\SUBLIM~1\Packages\requests\all\requests\sessions.py", line 642, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\tylerS\AppData\Roaming\SUBLIM~1\Packages\requests\all\requests\adapters.py", line 439, in send
    timeout=timeout
  File "C:\Users\tylerS\AppData\Roaming\SUBLIM~1\Packages\requests\all\requests\packages\urllib3\connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "C:\Users\tylerS\AppData\Roaming\SUBLIM~1\Packages\requests\all\requests\packages\urllib3\connectionpool.py", line 356, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "./python3.3/http/client.py", line 1065, in request
  File "./python3.3/http/client.py", line 1102, in _send_request
UnicodeEncodeError: 'latin-1' codec can't encode character '\u052c' in position 124995: ordinal not in range(256)
WARNING:Sync Settings.sync_settings.libs.logger:{'message': 'Not Found', 'documentation_url': 'https://developer.github.com/v3/gists/#delete-a-gist'}
ERROR:Sync Settings.sync_settings.libs.logger:'latin-1' codec can't encode character '\u052c' in position 124995: ordinal not in range(256)
Traceback (most recent call last):
  File "C:\Users\tylerS\AppData\Roaming\Sublime Text 3\Installed Packages\Sync Settings.sublime-package\sync_settings/commands/create_and_upload.py", line 45, in create
    ).create(data)
  File "C:\Users\tylerS\AppData\Roaming\Sublime Text 3\Installed Packages\Sync Settings.sublime-package\sync_settings/libs/gist.py", line 36, in auth_wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\tylerS\AppData\Roaming\Sublime Text 3\Installed Packages\Sync Settings.sublime-package\sync_settings/libs/gist.py", line 66, in create
    return self.__do_request('post', self.make_uri(), data=sublime.encode_value(data, True)).json()
  File "C:\Users\tylerS\AppData\Roaming\Sublime Text 3\Installed Packages\Sync Settings.sublime-package\sync_settings/libs/gist.py", line 92, in __do_request
    response = getattr(requests, verb)(url, headers=self.headers, proxies=self.proxies, **kwargs)
  File "C:\Users\tylerS\AppData\Roaming\SUBLIM~1\Packages\requests\all\requests\api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "C:\Users\tylerS\AppData\Roaming\SUBLIM~1\Packages\requests\all\requests\api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\tylerS\AppData\Roaming\SUBLIM~1\Packages\requests\all\requests\sessions.py", line 522, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\tylerS\AppData\Roaming\SUBLIM~1\Packages\requests\all\requests\sessions.py", line 642, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\tylerS\AppData\Roaming\SUBLIM~1\Packages\requests\all\requests\adapters.py", line 439, in send
    timeout=timeout
  File "C:\Users\tylerS\AppData\Roaming\SUBLIM~1\Packages\requests\all\requests\packages\urllib3\connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "C:\Users\tylerS\AppData\Roaming\SUBLIM~1\Packages\requests\all\requests\packages\urllib3\connectionpool.py", line 356, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "./python3.3/http/client.py", line 1065, in request
  File "./python3.3/http/client.py", line 1102, in _send_request
UnicodeEncodeError: 'latin-1' codec can't encode character '\u052c' in position 124995: ordinal not in range(256)
ERROR:Sync Settings.sync_settings.libs.logger:'latin-1' codec can't encode character '\u052c' in position 124995: ordinal not in range(256)
Traceback (most recent call last):
  File "C:\Users\tylerS\AppData\Roaming\Sublime Text 3\Installed Packages\Sync Settings.sublime-package\sync_settings/commands/create_and_upload.py", line 45, in create
    ).create(data)
  File "C:\Users\tylerS\AppData\Roaming\Sublime Text 3\Installed Packages\Sync Settings.sublime-package\sync_settings/libs/gist.py", line 36, in auth_wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\tylerS\AppData\Roaming\Sublime Text 3\Installed Packages\Sync Settings.sublime-package\sync_settings/libs/gist.py", line 66, in create
    return self.__do_request('post', self.make_uri(), data=sublime.encode_value(data, True)).json()
  File "C:\Users\tylerS\AppData\Roaming\Sublime Text 3\Installed Packages\Sync Settings.sublime-package\sync_settings/libs/gist.py", line 92, in __do_request
    response = getattr(requests, verb)(url, headers=self.headers, proxies=self.proxies, **kwargs)
  File "C:\Users\tylerS\AppData\Roaming\SUBLIM~1\Packages\requests\all\requests\api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "C:\Users\tylerS\AppData\Roaming\SUBLIM~1\Packages\requests\all\requests\api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\tylerS\AppData\Roaming\SUBLIM~1\Packages\requests\all\requests\sessions.py", line 522, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\tylerS\AppData\Roaming\SUBLIM~1\Packages\requests\all\requests\sessions.py", line 642, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\tylerS\AppData\Roaming\SUBLIM~1\Packages\requests\all\requests\adapters.py", line 439, in send
    timeout=timeout
  File "C:\Users\tylerS\AppData\Roaming\SUBLIM~1\Packages\requests\all\requests\packages\urllib3\connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "C:\Users\tylerS\AppData\Roaming\SUBLIM~1\Packages\requests\all\requests\packages\urllib3\connectionpool.py", line 356, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "./python3.3/http/client.py", line 1065, in request
  File "./python3.3/http/client.py", line 1102, in _send_request
UnicodeEncodeError: 'latin-1' codec can't encode character '\u052c' in position 124995: ordinal not in range(256)

**Comment by mfuentesg** [comment] 2020-06-30 22:44
hey @tumms which version are you using? latest ?

**Comment by tumms** [comment] 2020-06-30 22:59
Yes

**Comment by mfuentesg** [comment] 2020-06-30 23:07
Kindly share with me your gist url (if it is possible).

Do you have special chars in any file? This would be very helpful i.e `Ԭ`

**Comment by mfuentesg** [comment] 2020-06-30 23:40
@TheSecEng do you have any example with the same issue?, i am not able to reproduce it.

**Comment by TheSecEng** [comment] 2020-06-30 23:43
I’ll attempt to recreate

**Comment by mfuentesg** [comment] 2020-07-02 01:29
Closing because I am not able to reproduce it.

@tumms Feel free to reopen this issue or create a new one, if you are still facing the issue.

**Closed by mfuentesg** 2020-07-02 01:29 UTC
