### ISSUE TITLE
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 106-107: ordinal not in range(256)

### ISSUE THREAD

**Issue by monnerHenster** [mfuentesg/SyncSettings#164] opened 2020-06-24 13:40 UTC
ERROR:Sync Settings.sync_settings.libs.logger:'latin-1' codec can't encode characters in position 106-107: ordinal not in range(256)
Traceback (most recent call last):
  File "D:\软件\sublime Text\Data\Installed Packages\Sync Settings.sublime-package\sync_settings/commands/create_and_upload.py", line 45, in create
    ).create(data)
  File "D:\软件\sublime Text\Data\Installed Packages\Sync Settings.sublime-package\sync_settings/libs/gist.py", line 36, in auth_wrapper
    return func(self, *args, **kwargs)
  File "D:\软件\sublime Text\Data\Installed Packages\Sync Settings.sublime-package\sync_settings/libs/gist.py", line 66, in create
    return self.__do_request('post', self.make_uri(), data=sublime.encode_value(data, True)).json()
  File "D:\软件\sublime Text\Data\Installed Packages\Sync Settings.sublime-package\sync_settings/libs/gist.py", line 92, in __do_request
    response = getattr(requests, verb)(url, headers=self.headers, proxies=self.proxies, **kwargs)
  File "D:\软件\SUBLIM~2\Data\Packages\requests\all\requests\api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "D:\软件\SUBLIM~2\Data\Packages\requests\all\requests\api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "D:\软件\SUBLIM~2\Data\Packages\requests\all\requests\sessions.py", line 522, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\软件\SUBLIM~2\Data\Packages\requests\all\requests\sessions.py", line 642, in send
    r = adapter.send(request, **kwargs)
  File "D:\软件\SUBLIM~2\Data\Packages\requests\all\requests\adapters.py", line 439, in send
    timeout=timeout
  File "D:\软件\SUBLIM~2\Data\Packages\requests\all\requests\packages\urllib3\connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "D:\软件\SUBLIM~2\Data\Packages\requests\all\requests\packages\urllib3\connectionpool.py", line 356, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "./python3.3/http/client.py", line 1065, in request
  File "./python3.3/http/client.py", line 1102, in _send_request
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 106-107: ordinal not in range(256)

**Comment by marcovirtual** [comment] 2020-06-24 15:53
The same is happenning to me.

![sublime_text_mopOjDdDRw](https://user-images.githubusercontent.com/13058480/85589042-9b0d5000-b619-11ea-9bb5-57138fe349b1.png)

Help pls!

**Comment by mfuentesg** [comment] 2020-06-24 20:27
@TheSecEng  ^

**Comment by TheSecEng** [comment] 2020-06-24 21:27
Looking into this.

**Comment by TheSecEng** [comment] 2020-06-24 22:32
Fix in the pipeline

**Comment by TheSecEng** [comment] 2020-06-25 12:31
Just FYI, this issue is because we moved from `json` to sublime functions. JSON ensured ASCII characters. Gist API requires valid JSON, and valid JSON requires UTF-8. We will have to add a `encode("UTF-8")` before posting to Gist

**Comment by mfuentesg** [comment] 2020-06-25 16:16
@codecodero i have created a new version along to @TheSecEng to solve this issue, please once this is available in package control, let me know if it solves your issue.

**Comment by mfuentesg** [comment] 2020-06-25 18:35
@marcovirtual can you confirm if the issue is fixed? If yes, please close this issue.

**Comment by marcovirtual** [comment] 2020-06-25 23:15
Thank you @mfuentesg and @TheSecEng, I can confirm the issue has been resolved on my machines! 

Unfortunately as I'm not the one who opened the issue, I see no option to close it. Pinging @monnerHenster

**Comment by mfuentesg** [comment] 2020-06-25 23:25
Fixed

**Closed** 2020-06-25 23:25 UTC
